### ISSUE TITLE
默认开启了cache连接池，在websokcet的event handle中使用redis的时候仍然报错

### ISSUE THREAD

**Issue by HyperLife1119** [shuipf/think-swoole#1]
我使用的是原版的think-swoole，由于学习资源较少，就来这里请教您了
报错如下:
```
PHP Fatal error:  Uncaught Swoole\Error: Socket#15 has already been bound to another coroutine#135, reading of the same socket in coroutine#136 at the same time is not allowed in /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/cache/driver/Redis.php:116
Stack trace:
#0 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/cache/driver/Redis.php(116): Redis->get()
#1 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/session/driver/Cache.php(38): think\cache\driver\Redis->get()
#2 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/session/Store.php(83): think\session\driver\Cache->read()
#3 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/Manager.php(174): think\session\Store->init()
#4 [internal function]: think\Manager->__call()
#5 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/Facade.php(96): call_user_func_array()
#6 /www/wwwroot/xxxxx/app/websocket/Handler.php(58): think\Facade::__callStati in /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/cache/driver/Redis.php on line 116

```
我使用的是 `Cache::store('redis')->handler()` 来获取redis实例
查阅了一下swoole的文档，说要用连接池，但我已经开启了cache连接池，仍然出现该问题

跟这个问题类似，只不过我的问题是redis
https://github.com/top-think/think-swoole/issues/134

**Comment by shuipf** [comment]
你最好用原版最新版（dev），它很多连接池的问题都修复了，但是还没发新版。

**Comment by HyperLife1119** [comment]
好的，我试试，谢谢你，可否留个QQ，方便日后请教问题😃



---原始邮件---
发件人: "水平凡"<notifications@github.com&gt;
发送时间: 2020年7月23日(周四) 上午8:56
收件人: "shuipf/think-swoole"<think-swoole@noreply.github.com&gt;;
抄送: "HyperLife1119"<1838491745@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [shuipf/think-swoole] 默认开启了cache连接池，在websokcet的event handle中使用redis的时候仍然报错 (#1)




 
你最好用原版最新版（dev），它很多连接池的问题都修复了，但是还没发新版。
